### ISSUE TITLE
Document Pelias Service API

### ISSUE THREAD

**Issue by riordan** [pelias/pelias-doc#1]
_From @riordan on September 8, 2015 20:51_

Part of Pelias Service Documentation story (pelias/pelias#124)

Complete documentation for Pelias / Mapzen Search service API.

Should document all:
- API Calls
- Parameters
- Responses
- Core caveats (e.g. CORS)

_Copied from original issue: pelias/api#227_

**Comment by riordan** [comment]
I've been using [Swagger](http://swagger.io) to stub out the API documentation, starting from the parameters, and moving to description.

My work's been happening in the [1.0swagger branch](https://github.com/pelias/pelias-doc/tree/1.0swagger) and the [swagger editor](https://editor.swagger.io). However, you should note that the editor only saves to browser localstorage (even when you run the server locally). Prepare to copy/paste to save to the repository.

**Comment by riordan** [comment]
@dianashk: mind helping out on stubbing out more of the parameters?

**Comment by rmglennon** [comment]
Other things:
- description of the data sources used in Mapzen Search
- more on layers - perhaps pull layers and data sources into a separate topic and link to it from the 002-search topic
- working examples and API keys
- more on the overview
- glossary or common term list

**Comment by dianashk** [comment]
@rmglennon @riordan can this be closed?

**Comment by riordan** [comment]
Yep!
