### ISSUE TITLE
glossary and terms and clarifications

### ISSUE THREAD

**Issue by burritojustice** [pelias/pelias-doc#10]
build a glossary! here are a few to start with

- [ ] coarse
- [ ] fine
- [ ] geocoding
- [ ] forward geocoding (from Rhonda - this term is in the get started topic now)
- [ ] reverse geocoding
- [ ] bounding box
- [ ] endpoint (API)
- [ ] place (API) 
- [x] gazetteer
- [ ] CORS
- [ ] layer(s)
- [ ] point
- [ ] latitude
- [ ] longitude
- [ ] Coordinate System / WGS84
...

**Comment by missinglink** [comment]
pretty sure this is a 'gazetteer`?

![lol](http://i1223.photobucket.com/albums/dd511/RyanHasGIFS/GIFS/1238409599nomnomn.gif)

**Comment by riordan** [comment]
Closed by #46
