### ISSUE TITLE
Some search query examples are broken in the docs

### ISSUE THREAD

**Issue by rmglennon** [pelias/pelias-doc#108]
The documentation has examples of building different queries throughout. Some work and some do not.

On the responses page: https://mapzen.com/documentation/search/response/

This query 
https://search.mapzen.com/v1/search?api_key=search-XXXXXXX&text=YMCA&size=25

results in <message>'search-XXXXXXX' is not a valid key.</message>

Some other queries do work, like this one: 
https://search.mapzen.com/v1/reverse?api_key=search-XXXXXXX&point.lat=48.858268&point.lon=2.294471

Perhaps it's a caching thing, where the cached locations work? Either way, let's fix.

**Comment by orangejulius** [comment]
Yeah, if someone else with a valid API key has run exactly the query listed with the XXXXXX api key, it will work. It also requires that the query was run from the same general area, or enough time has elapsed for Fastly to propogate the cached response to all its points of presence. So it's something that's quite hard to prevent from happening.

The solution would be something like a script that runs all the queries from the documentation every time we clear the Fastly cache.

**Comment by orangejulius** [comment]
What if we made an API key specifically for documentation? It could probably have a low rate limit, since all the queries in the docs would (likely) be cached.

**Comment by rmglennon** [comment]
Yes, I think this a new, real, limited the way to go (other than having an actual key with xxxxx!). There are some other discussions about future options for keys, but in the meantime, I will chat with ops folks on proper rates for search and turn-by-turn.
