### ISSUE TITLE
Multiple boundaries GIF image has incorrect final boundary

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias-doc#11]
![multiple boundaries](https://github.com/dianashk/pelias-doc/raw/master/getting-started/overlapping_boundaries.gif)

I hate to criticize this otherwise amazing GIF, but in the final frame, the red shape for the final searched area extends below the southern end of the bounding box (green). It has the effect of suggesting that we would ignore the bounding box in this case, which is of course false.

**Comment by rmglennon** [comment]
I see what you're saying. Good eye. The stuff in the red box shouldn't be included because it's out of the green stripe.

![image](https://cloud.githubusercontent.com/assets/4380498/10155456/404f7916-662a-11e5-8cbd-6099fdb890d6.png)

**Comment by dianashk** [comment]
Ooops! My bad. I'll try to fix it tomorrow.

**Comment by rmglennon** [comment]
Fixed in PR #27
