### ISSUE TITLE
Update doc for `/place` to reflect new gid warnings

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias-doc#113]
It still encourages building the gids and also has a statement that I can't parse after several reads.

**Comment by orangejulius** [comment]
Things are looking a lot better in the [/place docs](https://github.com/pelias/pelias-doc/blob/9b170bacc97bfdfcaa4dc7a9053ef19a2853b855/place.md after pelias/pelias-doc#110 and pelias/pelias-doc#114.

I think we've removed all the parts that would encourage building IDs, is there anywhere that's still confusing?

**Comment by dianashk** [comment]
I think we're good. Closing this issue.
