### ISSUE TITLE
Index page needs something to break up the wall of text

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias-doc#123]
Emoji, images, titles, anything will help prevent new users first looking at the docs from seeing [a wall of text](https://github.com/pelias/pelias-doc/blob/master/index.md).

![screenshot from 2016-06-13 14-52-10](https://cloud.githubusercontent.com/assets/111716/16019329/732b8dc6-3176-11e6-96ab-4bb7389977e8.png)

**Comment by kkowalsky** [comment]
I agree @orangejulius, what about a GIF of someone searching with one of the use cases described in the first paragraph?

**Comment by orangejulius** [comment]
That would be great. We currently have [pretty nice GIFs](https://github.com/pelias/pelias/blob/master/README.md) in the readme of the pelias/pelias repo, but they're really old. There's nothing fundamentally wrong with them but they were made before we even had our own tile themes. It would be awesome to get newer GIFs made. Perhaps our resident GIF expert @burritojustice can help.
