### ISSUE TITLE
remove rate limits and link to documentation overview

### ISSUE THREAD

**Issue by kkowalsky** [pelias/pelias-doc#175]
we should streamline where we mention specific rate limits: https://mapzen.com/documentation/search/api-keys-rate-limits/

and link to https://mapzen.com/documentation/search/api-keys-rate-limits/ instead

cc/ @rmglennon

**Comment by migurski** [comment]
Guessing you meant this for the 2nd link: https://mapzen.com/documentation/overview/#rate-limits
