### ISSUE TITLE
Add fancy images for search topic

### ISSUE THREAD

**Issue by rmglennon** [pelias/pelias-doc#25]
Putting in a "to do" to update and resize the images in the main search topic (now called search.md). These are large and there's work going on with graphics folks.

See also #11.

**Comment by kkowalsky** [comment]
@rmglennon how much smaller do we want them?

**Comment by rmglennon** [comment]
@kkowalsky they don't necessarily need to be smaller because they seem to resize OK in the available page width these days (the search docs were created at the start of having a help system). They mostly could use cleanup/prettifying -- for example, some have an extra border at the top, pixelated boundaries and text, and no attribution -- and we didn't get around to doing this...

**Comment by kkowalsky** [comment]
@rmglennon "resize" was misleading, will crop & "prettify" the images
