### ISSUE TITLE
What does the confidence score represent?

### ISSUE THREAD

**Issue by hampelm** [pelias/pelias-doc#36]
And can you provide some context / examples for interpreting confidence scores? Some results that appear to be dead on share very similar scores in the mid-80s with results 100 miles+ off.

**Comment by orangejulius** [comment]
Hey @hampelm,
I've written up a description of the confidence score for the docs, and it will be merged in soon. You can view it [here](https://github.com/pelias/pelias-doc/blob/describe-notable-response-features/response.md#notable-features) for now.

The easiest example is probably querying for an address, like [11 broadway, new york, ny](http://search.mapzen.com/v1/search?api_key=search-XXXXXX&text=11%20broadway,%20new%20york,%20NY).

When you do a query like this, our address parser takes a look at the `text` parameter and tries to make heads or tails of it. It's not nearly as smart as it could be right now, but in this case it does a good job and comes up with the following guess about the address that is put in the `geocoding` block at the top of the response:

    "parsed_text": {
        "name": "11 broadway",
        "state": "NY",
        "regions":    [
          "11 broadway",
          "new york"
        ],
        "admin_parts": "new york, NY"
    }

The first two results are records for the actual 11 Broadway, one from OpenAddresses and one from OpenStreetMap. They both match all these fields pretty much perfectly, so their score is `0.942`.

Further down in the results you'll find `11 Old Broadway, Manhattan, NY`, which isn't quite as perfect of a match so its score is `0.658`.
Interestingly, `11 Broadway, Queens, NY` is next after that, and while it's further down in the results, its score is `0.709`. This reveals the secret that the order of the results is determined by the scoring done by Elasticsearch, while the confidence score is determined by code in our API layer. Ideally they'd be the same but there are some things that are much easier to do in our API.

For example, if you change the query to [11 broadway, new york, NY 10005](http://search.mapzen.com/v1/search?api_key=search-XXXXXX&text=11%20broadway,%20new%20york,%20NY%2010005), the confidence score for those first two results goes down to `0.5`. The actual zip code for 11 Broadway is 10004, and there's a cap of 0.5 for results that don't match the expected zipcode.

The confidence score is pretty new, so if you have suggestions for how we can improve it we'd love to hear from you. If you find any cases where it seems particularly bad (or good!), please send them along. Also the code can be found [here](https://github.com/pelias/api/blob/master/middleware/confidenceScore.js) and [here](https://github.com/pelias/api/blob/master/middleware/confidenceScoreReverse.js) if you want _all_ the details.

**Comment by orangejulius** [comment]
Hey @hampelm, we're closing this issue just because it's been a while and we need to periodically clean out old issues to better keep track of things. I'm fairly certain we've answered your question but if not, or if you have any others, feel free to open another issue. We have a [Gitter](https://gitter.im/pelias/pelias) chatroom as well.

Thanks!

**Comment by hampelm** [comment]
Thanks for the detailed response and apologies for my delayed reply! This very much helps answer the question.
