### ISSUE TITLE
Use of predicates

### ISSUE THREAD

**Issue by costales** [pelias/pelias-doc#37]
Hi!

Can I search with Pelias OSM tag places (ex tourism=camp_site)? I'd like to search for example, near Gas Stations, Campings... to a point.

Thanks in advance!

**Comment by orangejulius** [comment]
Howdy!

We filter down to a pretty [minimal](https://github.com/pelias/openstreetmap/blob/master/config/features.js) set of tags from OSM to keep the size of our index down. I think a full OSM planet imported into Elasticsearch would come in around 600GB, our entire index with all our datasources is only 70GB, so much more manageable. 

So Mapzen's hosted pelias at search.mapzen.com probably won't add too many more tags in the future (although we almost certainly will add some), but if you have a particular use case in mind, you can probably set up an instance yourself to do what you want, especially if it's not an entire planet import. We'd be happy to answer questions you have along the way if you decide to try it out.

**Comment by costales** [comment]
Hi Julian!
I'll take a look :) Thanks a lot for your respond!

**Comment by dianashk** [comment]
Sounds like the functionality you're interested in is category search. We are working on a category taxonomy before we make that feature publicly available. The tags won't match the OSM tags exactly, but you will be able to reference our taxonomy for the supported categories. 

We will have more info in the next two weeks on the timeline for this functionality.

**Comment by costales** [comment]
Hi! Yes, we want to search nearby POIs into a radio, something, like Gas
Stations in 5km.
Thanks a lot :)

**Comment by riordan** [comment]
We're looking at this as a core feature around category search. It's a big challenge to figure out the taxonomy issues across Mapzen. 

To track it, it's going to be the issue pelias/pelias#150.
