### ISSUE TITLE
Include `size` parameter in Search documentation

### ISSUE THREAD

**Issue by riordan** [pelias/pelias-doc#40]
No illustration of search size

**Comment by orangejulius** [comment]
Looks like we should move the section at the end of https://github.com/pelias/pelias-doc/blob/master/response.md to the /search and /reverse endpoint pages

**Comment by rmglennon** [comment]
Looks covered in the reverse topic. https://github.com/pelias/pelias-doc/blob/master/reverse.md#size

But not in the search topic.

**Comment by rmglennon** [comment]
closed with PR #44
