### ISSUE TITLE
Specification driven API documentation

### ISSUE THREAD

**Issue by riordan** [pelias/pelias-doc#68]
In addition to narrative documentation, we should write a specification based documentation, giving maximum and minimums, types, etc to serve as quick documentation and to form the basis for an API explorer.

**Comment by dianashk** [comment]
Let's see if we can use something like [this](https://github.com/tripit/slate)

**Comment by riordan** [comment]
To the backlog!

**Comment by dianashk** [comment]
We now have the [Search Explorer](mapzen.com/search/explorer) and any future spec-driven docs would probably live in there.
