### ISSUE TITLE
Verify that pelias.json is a documented thing

### ISSUE THREAD

**Issue by riordan** [pelias/pelias-doc#81]

**Comment by orangejulius** [comment]
+1

**Comment by orangejulius** [comment]
Also make sure to add things such as logging verboseness (see pelias/vagrant#29)

**Comment by orangejulius** [comment]
This is covered pretty well by the [config section](https://github.com/pelias/pelias-doc/blob/master/installing.md#customize-pelias-config) in our installation docs.
