### ISSUE TITLE
update leaflet geocoder tutorial to reflect files on cdnjs and its name

### ISSUE THREAD

**Issue by rmglennon** [pelias/pelias-doc#84]
We now have the plug-in on http://cdnjs.com/libraries/leaflet-geocoder-mapzen (woohoo, @louh). The source files have also been renamed and moved to the mapzen org (although they do redirect on GitHub).

To update:
1) Change the text of the tutorial
2) Remove the code files from the zip in this repo.
3) Poke around for any other references to it on mapzen.com and the blog.

**Comment by louh** [comment]
I've done a search & replace to the new repository on the blog already.
