### ISSUE TITLE
Convert Pelias setup tutorial blog post into a documentation page

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias-doc#88]
@sevko wrote a [great blog post](https://mapzen.com/blog/pelias-setup-tutorial), but it's now out of date. We need to rewrite that blog post in an up to date way, and then change the blog page to a 301 permanent redirect to the documentation, so that no one is reading out of date docs.

**Comment by dianashk** [comment]
Great catch. Let's do this in conjunction with setting up the new importer plugin ecosystem.

**Comment by orangejulius** [comment]
I'm realizing now that this is really a tutorial for the [vagrant image](https://github.com/pelias/vagrant) and is still mostly relevant, but separate from our recently created [full, manual installation docs](https://github.com/pelias/pelias-doc/blob/master/installing.md). This blog post should probably still be integrated into the Vagrant readme so that it stays up to date.

**Comment by orangejulius** [comment]
The blog post now has some headers that redirect people to the installation docs!
